services:

  command_bus:
    class: App\Messenger\Application\Service\CommandBus\CommandBus

  system:
    class: App\Messenger\Application\System
    arguments: ['@command_bus']

  filesystem:
    class: Symfony\Component\Filesystem\Filesystem